#!/usr/bin/env bash
# Self-host the full RoboTunnel open-source stack on a single Ubuntu VPS.
#
# What this script installs:
#   - robotunneld          (Rust daemon; from source or a release binary)
#   - tunnel-svc           (Go signaling/relay; from source or a release binary)
#   - robot-agent-registry (Go registry; from source or a release binary)
#   - coturn               (TURN server; via apt)
#   - Caddy                (reverse proxy + TLS; via apt)
#
# Pre-requisites (you must supply):
#   1. A VPS with Ubuntu 22.04+ and ports 80, 443, 3478, 5349, 11411, 49152-65535 open.
#   2. DNS A records pointing to the VPS:
#        tunnel.example.com
#        reg.example.com
#        turn.example.com
#   3. This script run as root.
#
# Usage:
#   export DOMAIN=example.com
#   export ADMIN_EMAIL=you@example.com
#   sudo -E bash self-host-full.sh
#
# After install, edit /opt/robotunnel/config/.env and restart services.

set -euo pipefail

DOMAIN="${DOMAIN:?Set DOMAIN=example.com}"
ADMIN_EMAIL="${ADMIN_EMAIL:?Set ADMIN_EMAIL=you@example.com}"

INSTALL_DIR=/opt/robotunnel
CONFIG_DIR=$INSTALL_DIR/config
BIN_DIR=$INSTALL_DIR/bin

echo "==> Installing system packages"
apt-get update -qq
apt-get install -y --no-install-recommends \
    curl ca-certificates gnupg lsb-release \
    coturn \
    debian-keyring debian-archive-keyring

echo "==> Installing Caddy"
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] \
https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" \
    > /etc/apt/sources.list.d/caddy-stable.list
apt-get update -qq && apt-get install -y caddy

echo "==> Creating directories"
mkdir -p "$BIN_DIR" "$CONFIG_DIR"
useradd --system --no-create-home --shell /usr/sbin/nologin robotunnel 2>/dev/null || true
chown -R robotunnel:robotunnel "$INSTALL_DIR"

echo "==> Generating secrets (if not already present)"
ENV_FILE="$CONFIG_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    TURN_SECRET=$(openssl rand -hex 32)
    INTERNAL_API_SECRET=$(openssl rand -hex 32)
    RT_AGENT_AUTH_SEED_HEX=$(openssl rand -hex 32)

    cat > "$ENV_FILE" <<EOF
# RoboTunnel self-hosted configuration
# Generated by self-host-full.sh — edit as needed.

DOMAIN=$DOMAIN
ADMIN_EMAIL=$ADMIN_EMAIL

# Tunnel signaling service (tunnel-svc)
DATABASE_URL=sqlite://$CONFIG_DIR/tunnel.db
TURN_SECRET=$TURN_SECRET
RT_AGENT_AUTH_SEED_HEX=$RT_AGENT_AUTH_SEED_HEX
INTERNAL_API_SECRET=$INTERNAL_API_SECRET
TURN_URLS=turn:turn.$DOMAIN:3478

# Registry (robot-agent-registry)
REGISTRY_DATABASE_URL=sqlite://$CONFIG_DIR/registry.db
REGISTRY_JWT_SECRET=$(openssl rand -hex 32)

# Daemon (robotunneld)
RT_REGISTRY_URL=https://reg.$DOMAIN
RT_DAEMON_LISTEN_PORT=11411
RT_DAEMON_INSECURE=false
EOF
    chmod 600 "$ENV_FILE"
    echo "    Generated secrets in $ENV_FILE"
else
    echo "    $ENV_FILE already exists — skipping secret generation"
fi

echo "==> Configuring coturn"
cat > /etc/turnserver.conf <<'TURN_EOF'
# Generated by self-host-full.sh
TURN_EOF
# Inline the config with variables expanded
source "$ENV_FILE"
cat >> /etc/turnserver.conf <<EOF
external-ip=$(curl -s https://api.ipify.org 2>/dev/null || echo "127.0.0.1")
listening-port=3478
tls-listening-port=5349
use-auth-secret
static-auth-secret=$TURN_SECRET
cert=/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.$DOMAIN/turn.$DOMAIN.crt
pkey=/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.$DOMAIN/turn.$DOMAIN.key
min-port=49152
max-port=65535
no-stun
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
log-file=/var/log/coturn/turnserver.log
simple-log
no-stdout-log
EOF
mkdir -p /var/log/coturn
chown coturn:coturn /var/log/coturn

echo "==> Writing Caddyfile"
cat > /etc/caddy/Caddyfile <<EOF
# Tunnel signaling / relay
tunnel.$DOMAIN {
    reverse_proxy localhost:8091
}

# Agent registry
reg.$DOMAIN {
    reverse_proxy localhost:8090
}

# TURN (TLS termination for port 5349)
turn.$DOMAIN {
    # coturn handles TLS itself on 5349; this vhost just acquires the cert via HTTP-01
    respond "TURN server managed by coturn on port 3478/5349"
}
EOF

echo "==> Writing systemd units"

cat > /etc/systemd/system/robotunnel-tunnel.service <<EOF
[Unit]
Description=RoboTunnel tunnel-svc (signaling + relay)
After=network.target

[Service]
User=robotunnel
EnvironmentFile=$ENV_FILE
ExecStart=$BIN_DIR/tunnel-svc
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/robotunnel-registry.service <<EOF
[Unit]
Description=RoboTunnel agent registry
After=network.target

[Service]
User=robotunnel
EnvironmentFile=$ENV_FILE
ExecStart=$BIN_DIR/robot-agent-registry
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/robotunneld.service <<EOF
[Unit]
Description=RoboTunnel daemon (agent-to-agent tunneling)
After=network.target

[Service]
User=robotunnel
EnvironmentFile=$ENV_FILE
ExecStart=$BIN_DIR/robotunneld
Restart=on-failure
RestartSec=5
RuntimeDirectory=robotunnel
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
EOF

echo "==> Enabling and starting services"
systemctl daemon-reload
systemctl enable --now coturn
systemctl enable --now caddy
# tunnel-svc, registry, and robotunneld need binaries first:
systemctl enable robotunnel-tunnel robotunnel-registry robotunneld || true

cat <<'DONE'

============================================================
 Self-host setup complete!
============================================================

NEXT STEPS:

1. Build or download the binaries and place them in:
     /opt/robotunnel/bin/tunnel-svc
     /opt/robotunnel/bin/robot-agent-registry
     /opt/robotunnel/bin/robotunneld

   Build from source:
     # tunnel-svc (Go)
     cd go && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
         go build -o /opt/robotunnel/bin/tunnel-svc ./cmd/tunnel-svc

     # robot-agent-registry (Go)
     cd ../robot-agent-registry && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
         go build -o /opt/robotunnel/bin/robot-agent-registry .

     # robotunneld (Rust)
     cd ../robot-agent-tunnel/rust && \
         cargo build --release -p robotunneld && \
         cp target/release/robotunneld /opt/robotunnel/bin/

2. Start the services:
     systemctl start robotunnel-tunnel robotunnel-registry robotunneld

3. Verify:
     curl https://tunnel.$DOMAIN/health
     curl https://reg.$DOMAIN/health

4. TURN: coturn needs the TLS certificates that Caddy has acquired.
   Re-run or point coturn at the Caddy cert paths in /etc/turnserver.conf.
   Then: systemctl restart coturn

5. Edit /opt/robotunnel/config/.env to tune any settings.

DONE
